# Generated by Django 3.1.6 on 2022-04-15 10:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jdafinancialsapp', '0013_restest'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ResTest',
        ),
        migrations.RemoveField(
            model_name='companymodel',
            name='shareholder',
        ),
        migrations.AddField(
            model_name='shareholdermodel',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='jdafinancialsapp.companymodel'),
        ),
    ]
