# Generated by Django 3.1.6 on 2022-04-15 15:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jdafinancialsapp', '0014_auto_20220415_1028'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shareholdermodel',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='shareholders', to='jdafinancialsapp.companymodel'),
        ),
        migrations.AlterModelTable(
            name='shareholdermodel',
            table='ShareholderModel',
        ),
    ]
