# Generated by Django 3.1.6 on 2022-04-15 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jdafinancialsapp', '0015_auto_20220415_1548'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shareholdermodel',
            name='shrhldr_type',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='shareholdermodel',
            name='shrs_hld',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True),
        ),
    ]
