# Generated by Django 3.1.6 on 2022-04-17 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jdafinancialsapp', '0016_auto_20220415_1601'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResTest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
    ]
