# Generated by Django 3.1.6 on 2022-04-17 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jdafinancialsapp', '0017_restest'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResTes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('restes_name', models.CharField(blank=True, max_length=20, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='restest',
            name='restes_name',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
    ]
