# Generated by Django 3.1.6 on 2022-04-17 15:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jdafinancialsapp', '0018_auto_20220417_1054'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ResTes',
        ),
        migrations.DeleteModel(
            name='ResTest',
        ),
    ]
