# Generated by Django 3.1.6 on 2022-04-17 15:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jdafinancialsapp', '0019_auto_20220417_1116'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ShareholderModel',
        ),
    ]
