# Generated by Django 3.1.6 on 2022-04-17 19:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jdafinancialsapp', '0020_delete_shareholdermodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShareholderModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shrhldr_name', models.CharField(blank=True, max_length=100, null=True)),
                ('shrhldr_type', models.CharField(blank=True, max_length=50, null=True)),
                ('shrs_hld', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='shareholders', to='jdafinancialsapp.companymodel')),
            ],
            options={
                'verbose_name_plural': 'ShareholderModel',
                'db_table': 'ShareholderModel',
            },
        ),
    ]
