# Generated by Django 3.1.6 on 2022-04-29 13:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jdafinancialsapp', '0021_shareholdermodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companymodel',
            name='company',
            field=models.CharField(blank=True, max_length=200, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='companymodel',
            name='legl_form',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='companymodel',
            name='sector',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='jdafinancialsapp.sectormodel'),
        ),
    ]
