# Generated by Django 3.1.6 on 2022-04-29 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jdafinancialsapp', '0023_auto_20220429_0946'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exchangemodel',
            name='acronym',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='exchangemodel',
            name='name',
            field=models.CharField(max_length=225),
        ),
    ]
