# Generated by Django 3.1.6 on 2022-04-29 19:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jdafinancialsapp', '0025_auto_20220429_1057'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ExchangeModel',
        ),
    ]
