# Generated by Django 3.1.6 on 2022-05-13 19:43

from django.db import migrations, models
import django.db.models.deletion
import phone_field.models


class Migration(migrations.Migration):

    dependencies = [
        ('jdafinancialsapp', '0026_delete_exchangemodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='AddressModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('addr', models.CharField(blank=True, max_length=250, null=True)),
                ('phone_nbr', phone_field.models.PhoneField(blank=True, help_text='Contact phone number', max_length=31)),
                ('fax_nbr', phone_field.models.PhoneField(blank=True, help_text='Contact fax number', max_length=31)),
                ('email', models.EmailField(blank=True, max_length=240, null=True)),
                ('website', models.URLField(blank=True, null=True)),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='addresses', to='jdafinancialsapp.companymodel')),
            ],
            options={
                'verbose_name_plural': 'AddressModel',
                'db_table': 'AddressModel',
            },
        ),
    ]
