# Generated by Django 3.1.6 on 2022-05-13 21:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jdafinancialsapp', '0027_addressmodel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='addressmodel',
            name='fax_nbr',
        ),
        migrations.RemoveField(
            model_name='addressmodel',
            name='phone_nbr',
        ),
        migrations.AlterUniqueTogether(
            name='financialstatementlinesequencemodel',
            unique_together={('financial_statement', 'financial_statement_line', 'sequence')},
        ),
    ]
