# Generated by Django 3.1.6 on 2022-05-13 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jdafinancialsapp', '0028_auto_20220513_1737'),
    ]

    operations = [
        migrations.AddField(
            model_name='addressmodel',
            name='fax_nbr',
            field=models.CharField(blank=True, help_text='Contact fax number', max_length=30),
        ),
        migrations.AddField(
            model_name='addressmodel',
            name='phone_nbr',
            field=models.CharField(blank=True, help_text='Contact phone number', max_length=30),
        ),
    ]
