# Generated by Django 3.1.6 on 2022-05-14 01:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jdafinancialsapp', '0029_auto_20220513_1744'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shareholdermodel',
            name='shrhldr_type',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
