# Generated by Django 3.1.6 on 2022-05-14 01:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jdafinancialsapp', '0030_auto_20220513_2132'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companymodel',
            name='actvty_code',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='companymodel',
            name='actvty_sctr',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='companymodel',
            name='intrnl_actvty_code',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='companymodel',
            name='legl_form',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='companymodel',
            name='othr_bus_sctr',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='companymodel',
            name='rccm_nbr',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
