# Generated by Django 3.1.6 on 2022-05-14 01:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jdafinancialsapp', '0031_auto_20220513_2150'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addressmodel',
            name='fax_nbr',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='addressmodel',
            name='phone_nbr',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.CreateModel(
            name='LeadersModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lst_name', models.CharField(max_length=100)),
                ('func', models.CharField(blank=True, max_length=50, null=True)),
                ('phone_nbr', models.CharField(blank=True, max_length=30, null=True)),
                ('email', models.EmailField(blank=True, max_length=240, null=True)),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='leaders', to='jdafinancialsapp.companymodel')),
            ],
            options={
                'verbose_name_plural': 'LeadersModel',
                'db_table': 'LeadersModel',
            },
        ),
    ]
