# Generated by Django 3.1.6 on 2022-05-17 19:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jdafinancialsapp', '0032_auto_20220513_2159'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubsidiaryModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=200)),
                ('share_amt', models.IntegerField(blank=True, null=True)),
                ('url', models.URLField(blank=True, max_length=100, null=True)),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subsidaries', to='jdafinancialsapp.companymodel')),
            ],
            options={
                'verbose_name_plural': 'SubsidiaryModel',
                'db_table': 'SubsidiaryModel',
            },
        ),
        migrations.CreateModel(
            name='ParentCompanyModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('legl_name', models.CharField(max_length=200)),
                ('comm_name', models.CharField(blank=True, max_length=200, null=True)),
                ('cntry', models.CharField(blank=True, max_length=30, null=True)),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='parentcompany', to='jdafinancialsapp.companymodel')),
            ],
            options={
                'verbose_name_plural': 'ParentCompanyModel',
                'db_table': 'ParentCompanyModel',
            },
        ),
    ]
