# Generated by Django 3.1.6 on 2022-05-21 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jdafinancialsapp', '0034_auto_20220517_1544'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shareholdermodel',
            name='company',
        ),
        migrations.AddField(
            model_name='shareholdermodel',
            name='company',
            field=models.ManyToManyField(blank=True, null=True, related_name='shareholders', to='jdafinancialsapp.CompanyModel'),
        ),
    ]
