# Generated by Django 3.1.6 on 2022-05-21 22:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jdafinancialsapp', '0035_auto_20220521_1314'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shareholdermodel',
            name='company',
        ),
        migrations.AddField(
            model_name='shareholdermodel',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='shareholders', to='jdafinancialsapp.companymodel'),
        ),
    ]
