# Generated by Django 3.1.6 on 2022-05-24 02:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jdafinancialsapp', '0036_auto_20220521_1854'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResTest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('restes_name', models.CharField(blank=True, max_length=25, null=True)),
            ],
        ),
    ]
