# Generated by Django 3.1.6 on 2022-05-24 02:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jdafinancialsapp', '0037_restest'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AddressModel',
        ),
    ]
