# Generated by Django 3.1.6 on 2022-05-24 02:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jdafinancialsapp', '0038_delete_addressmodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='AddressModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('addr', models.CharField(blank=True, max_length=250, null=True)),
                ('phone_nbr', models.CharField(blank=True, max_length=30, null=True)),
                ('fax_nbr', models.CharField(blank=True, max_length=30, null=True)),
                ('email', models.EmailField(blank=True, max_length=240, null=True)),
                ('website', models.URLField(blank=True, null=True)),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='addresses', to='jdafinancialsapp.companymodel')),
            ],
            options={
                'verbose_name_plural': 'AddressModel',
                'db_table': 'AddressModel',
            },
        ),
    ]
