# Generated by Django 3.1.6 on 2022-05-25 01:34

from django.db import migrations, models
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('jdafinancialsapp', '0039_addressmodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='CountryModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', django_countries.fields.CountryField(blank=True, max_length=2, null=True, unique=True)),
                ('world_region', models.CharField(blank=True, max_length=15, null=True)),
                ('crncy', models.CharField(blank=True, max_length=3, null=True)),
                ('area', models.IntegerField(blank=True, null=True)),
                ('capl_city', models.CharField(max_length=200)),
                ('ofcl_lang', models.CharField(max_length=100)),
                ('ph_code', models.CharField(max_length=200)),
            ],
            options={
                'verbose_name_plural': 'CountryModel',
                'db_table': 'CountryModel',
            },
        ),
    ]
