# Generated by Django 3.1.6 on 2022-05-28 18:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jdafinancialsapp', '0040_countrymodel'),
    ]

    operations = [
        migrations.RenameField(
            model_name='countrymodel',
            old_name='world_region',
            new_name='continent',
        ),
    ]
