# Generated by Django 3.1.6 on 2022-05-29 16:43

from django.db import migrations, models
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('jdafinancialsapp', '0041_auto_20220528_1451'),
    ]

    operations = [
        migrations.AddField(
            model_name='countrymodel',
            name='prsdnt_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='countrymodel',
            name='area',
            field=django_countries.fields.CountryField(blank=True, max_length=2, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='countrymodel',
            name='capl_city',
            field=django_countries.fields.CountryField(blank=True, max_length=2, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='countrymodel',
            name='continent',
            field=django_countries.fields.CountryField(blank=True, max_length=2, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='countrymodel',
            name='ph_code',
            field=django_countries.fields.CountryField(blank=True, max_length=2, null=True, unique=True),
        ),
    ]
