# Generated by Django 3.1.6 on 2022-05-29 16:44

from django.db import migrations
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('jdafinancialsapp', '0042_auto_20220529_1243'),
    ]

    operations = [
        migrations.AlterField(
            model_name='countrymodel',
            name='crncy',
            field=django_countries.fields.CountryField(blank=True, max_length=2, null=True, unique=True),
        ),
    ]
