# Generated by Django 3.1.6 on 2022-05-30 13:27

from django.db import migrations
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('jdafinancialsapp', '0043_auto_20220529_1244'),
    ]

    operations = [
        migrations.AlterField(
            model_name='countrymodel',
            name='area',
            field=django_countries.fields.CountryField(blank=True, max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='countrymodel',
            name='capl_city',
            field=django_countries.fields.CountryField(blank=True, max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='countrymodel',
            name='continent',
            field=django_countries.fields.CountryField(blank=True, max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='countrymodel',
            name='crncy',
            field=django_countries.fields.CountryField(blank=True, max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='countrymodel',
            name='ph_code',
            field=django_countries.fields.CountryField(blank=True, max_length=2, null=True),
        ),
    ]
