# Generated by Django 3.1.6 on 2022-05-30 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jdafinancialsapp', '0044_auto_20220530_0927'),
    ]

    operations = [
        migrations.AlterField(
            model_name='countrymodel',
            name='area',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='countrymodel',
            name='crncy',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
