# Generated by Django 3.1.6 on 2022-05-30 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jdafinancialsapp', '0047_auto_20220530_1250'),
    ]

    operations = [
        migrations.AlterField(
            model_name='countrymodel',
            name='area',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
