# Generated by Django 3.1.6 on 2022-05-30 17:02

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('jdafinancialsapp', '0050_auto_20220530_1259'),
    ]

    operations = [
        migrations.AlterField(
            model_name='countrymodel',
            name='area',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='countrymodel',
            name='capl_city',
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='countrymodel',
            name='continent',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='countrymodel',
            name='crncy',
            field=models.CharField(blank=True, max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='countrymodel',
            name='ofcl_lang',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='countrymodel',
            name='ph_code',
            field=models.CharField(default=django.utils.timezone.now, max_length=25),
            preserve_default=False,
        ),
    ]
