# Generated by Django 3.1.6 on 2022-05-30 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jdafinancialsapp', '0052_auto_20220530_1303'),
    ]

    operations = [
        migrations.AlterField(
            model_name='countrymodel',
            name='area',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
