# Generated by Django 3.1.6 on 2022-05-30 19:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jdafinancialsapp', '0055_auto_20220530_1315'),
    ]

    operations = [
        migrations.CreateModel(
            name='EconomicDataModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('yr', models.IntegerField(blank=True, null=True)),
                ('popltn', models.IntegerField(blank=True, null=True)),
                ('popltn_grth_rate', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=18, null=True)),
                ('actv_popltn', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=18, null=True)),
                ('lf_exprn', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=18, null=True)),
                ('unemplmt_rate', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=18, null=True)),
                ('poverty_rate', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=18, null=True)),
                ('rnkg_bus', models.IntegerField(blank=True, default=0.0, null=True)),
                ('hsehold_cnsmptn', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=18, null=True)),
                ('idh', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=18, null=True)),
                ('country', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='econdata', to='jdafinancialsapp.countrymodel')),
            ],
            options={
                'verbose_name_plural': 'EconomicDataModel',
                'db_table': 'EconomicDataModel',
            },
        ),
    ]
