# Generated by Django 3.1.6 on 2022-06-03 18:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jdafinancialsapp', '0056_economicdatamodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='economicdatamodel',
            name='country',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='econs', to='jdafinancialsapp.countrymodel'),
        ),
        migrations.CreateModel(
            name='ElectionModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('elecn_dt', models.DateField()),
                ('elecn_type', models.CharField(blank=True, max_length=15, null=True)),
                ('cmnts', models.CharField(blank=True, max_length=250, null=True)),
                ('country', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='elections', to='jdafinancialsapp.countrymodel')),
            ],
            options={
                'verbose_name_plural': 'ElectionModel',
                'db_table': 'ElectionModel',
            },
        ),
    ]
