# Generated by Django 3.1.6 on 2022-06-04 16:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jdafinancialsapp', '0057_auto_20220603_1456'),
    ]

    operations = [
        migrations.CreateModel(
            name='EconomicZoneModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('econ_zone', models.CharField(blank=True, max_length=50, null=True)),
                ('country', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='econ_zones', to='jdafinancialsapp.countrymodel')),
            ],
            options={
                'verbose_name_plural': 'EconomicZoneModel',
                'db_table': 'EconomicZoneModel',
                'unique_together': {('country', 'econ_zone')},
            },
        ),
    ]
