# Generated by Django 3.1.6 on 2022-06-05 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jdafinancialsapp', '0058_economiczonemodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='countrymodel',
            name='continent',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='countrymodel',
            name='ph_code',
            field=models.CharField(max_length=50),
        ),
    ]
