# Generated by Django 3.1.6 on 2022-06-05 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jdafinancialsapp', '0059_auto_20220605_1701'),
    ]

    operations = [
        migrations.AlterField(
            model_name='countrymodel',
            name='capl_city',
            field=models.CharField(max_length=120),
        ),
        migrations.AlterField(
            model_name='countrymodel',
            name='continent',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='countrymodel',
            name='ofcl_lang',
            field=models.CharField(max_length=60),
        ),
        migrations.AlterField(
            model_name='countrymodel',
            name='ph_code',
            field=models.CharField(max_length=20),
        ),
    ]
