# Generated by Django 3.1.6 on 2022-06-06 00:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jdafinancialsapp', '0061_resmodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='economicdatamodel',
            name='popltn',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=18, null=True),
        ),
    ]
