# Generated by Django 3.1.6 on 2022-06-06 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jdafinancialsapp', '0064_economicdatamodel_gdp_rate'),
    ]

    operations = [
        migrations.AddField(
            model_name='economicdatamodel',
            name='gdp_prim_sctr',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=18, null=True),
        ),
    ]
