# Generated by Django 3.1.6 on 2022-06-06 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jdafinancialsapp', '0065_economicdatamodel_gdp_prim_sctr'),
    ]

    operations = [
        migrations.AddField(
            model_name='economicdatamodel',
            name='fixd_capl_invstmt',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=18, null=True),
        ),
        migrations.AddField(
            model_name='economicdatamodel',
            name='gdp_secy_sctr',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=18, null=True),
        ),
        migrations.AddField(
            model_name='economicdatamodel',
            name='gdp_tertry_sctr',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=18, null=True),
        ),
        migrations.AddField(
            model_name='economicdatamodel',
            name='gr_ntnl_prodt',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=18, null=True),
        ),
        migrations.AddField(
            model_name='economicdatamodel',
            name='ide',
            field=models.IntegerField(blank=True, default=0.0, null=True),
        ),
        migrations.AddField(
            model_name='economicdatamodel',
            name='mrgnl_lndg_rate',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=18, null=True),
        ),
    ]
