# Generated by Django 3.1.6 on 2022-06-06 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jdafinancialsapp', '0069_auto_20220606_1546'),
    ]

    operations = [
        migrations.AddField(
            model_name='economicdatamodel',
            name='dmstc_dbt',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='economicdatamodel',
            name='exp_amt',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='economicdatamodel',
            name='forgn_dbt',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='economicdatamodel',
            name='imp_amt',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='economicdatamodel',
            name='infltn_rate',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='economicdatamodel',
            name='pub_dbt',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='economicdatamodel',
            name='trd_bal',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='economicdatamodel',
            name='yr_dbt',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
