# Generated by Django 3.1.6 on 2022-06-06 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jdafinancialsapp', '0070_auto_20220606_1641'),
    ]

    operations = [
        migrations.AlterField(
            model_name='economicdatamodel',
            name='infltn_rate',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True),
        ),
    ]
