# Generated by Django 3.1.6 on 2022-06-06 22:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jdafinancialsapp', '0071_auto_20220606_1650'),
    ]

    operations = [
        migrations.CreateModel(
            name='OtherIndicatorsModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('yr', models.IntegerField(blank=True, null=True)),
                ('ind_name', models.CharField(blank=True, max_length=35, null=True)),
                ('ind_val', models.IntegerField(blank=True, null=True)),
                ('cmnts', models.CharField(blank=True, max_length=250, null=True)),
                ('country', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='other_indicators', to='jdafinancialsapp.countrymodel')),
            ],
            options={
                'verbose_name_plural': 'OtherIndicatorsModel',
                'db_table': 'OtherIndicatorsModel',
            },
        ),
    ]
