# Generated by Django 3.1.6 on 2022-06-10 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jdafinancialsapp', '0073_businesspartnersmodel'),
    ]

    operations = [
        migrations.RenameField(
            model_name='businesspartnersmodel',
            old_name='imp_exp_amt',
            new_name='exp_rate',
        ),
        migrations.RemoveField(
            model_name='businesspartnersmodel',
            name='imp_exp_code',
        ),
        migrations.AddField(
            model_name='businesspartnersmodel',
            name='exp_amt',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='businesspartnersmodel',
            name='imp_amt',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='businesspartnersmodel',
            name='imp_rate',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True),
        ),
    ]
