# Generated by Django 3.1.6 on 2022-06-10 13:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jdafinancialsapp', '0074_auto_20220610_0917'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='BusinessPartnersModel',
            new_name='TradePartnersModel',
        ),
        migrations.AlterModelOptions(
            name='tradepartnersmodel',
            options={'verbose_name_plural': 'TradePartnersModel'},
        ),
        migrations.AlterModelTable(
            name='tradepartnersmodel',
            table='TradePartnersModel',
        ),
    ]
