# Generated by Django 3.1.6 on 2022-06-13 00:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jdafinancialsapp', '0076_auto_20220612_2008'),
    ]

    operations = [
        migrations.AddField(
            model_name='tradepartnersmodel',
            name='exp_prodt_name',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='tradepartnersmodel',
            name='imp_prodt_name',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
