# Generated by Django 3.1.6 on 2022-06-13 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jdafinancialsapp', '0077_auto_20220612_2028'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otherindicatorsmodel',
            name='ind_val',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
