# Generated by Django 3.1.6 on 2022-06-13 20:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jdafinancialsapp', '0079_auto_20220613_1428'),
    ]

    operations = [
        migrations.CreateModel(
            name='EnergyModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('energy_yr', models.IntegerField(blank=True, null=True)),
                ('elec_hydro_dam_nbr', models.IntegerField(blank=True, null=True)),
                ('elec_pwr_sttn_nbr', models.IntegerField(blank=True, null=True)),
                ('elec_otr_nbr', models.IntegerField(blank=True, null=True)),
                ('crude_prodtn_amt', models.IntegerField(blank=True, null=True)),
                ('crude_exp_amt', models.IntegerField(blank=True, null=True)),
                ('crude_imp_amt', models.IntegerField(blank=True, null=True)),
                ('crude_rsrvs_amt', models.IntegerField(blank=True, null=True)),
                ('refined_prodtn_amt', models.IntegerField(blank=True, null=True)),
                ('refined_cnsmptn_amt', models.IntegerField(blank=True, null=True)),
                ('refined_exp_amt', models.IntegerField(blank=True, null=True)),
                ('refined_imp_amt', models.IntegerField(blank=True, null=True)),
                ('gas_prodtn_amt', models.IntegerField(blank=True, null=True)),
                ('gas_exp_amt', models.IntegerField(blank=True, null=True)),
                ('gas_imp_amt', models.IntegerField(blank=True, null=True)),
                ('gas_rsrv_amt', models.IntegerField(blank=True, null=True)),
                ('country', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='energies', to='jdafinancialsapp.countrymodel')),
            ],
            options={
                'verbose_name_plural': 'EnergyModel',
                'db_table': 'EnergyModel',
            },
        ),
    ]
