# Generated by Django 3.1.6 on 2022-09-17 14:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jdafinancialsapp', '0081_programmer'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Programmer',
        ),
    ]
