# Generated by Django 4.2 on 2025-05-29 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jdapublicationsapp', '0012_alter_publicationcompanymodel_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publicationmodel',
            name='research_type',
            field=models.CharField(choices=[('', 'Type'), ('Daily Briefing', 'Daily Briefing'), ('Quarterly Results', 'Quarterly Results'), ('Half Year Results', 'Half Year Results'), ('Annual Results', 'Annual Results'), ('Shareholder Meeting Feedback', 'Shareholder Meeting Feedback'), ('IPO Analysis', 'IPO Analysis'), ('Research Notes', 'Research Notes'), ('Sector Reports', 'Sector Reports'), ('Strategic Reports', 'Strategic Reports'), ('Economic Notes', 'Economic Notes'), ('Recommendation', 'Recommendation')], max_length=100),
        ),
    ]
