# Generated by Django 5.1.4 on 2026-06-20 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jdapublicationsapp', '0019_rename_half_year_results'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publicationmodel',
            name='research_type',
            field=models.CharField(choices=[('', 'Type'), ('Daily Briefing', 'Daily Briefing'), ('Quarterly Results', 'Quarterly Results'), ('Semi-annual Results', 'Semi-annual Results'), ('Annual Results', 'Annual Results'), ('Shareholder Meeting Feedback', 'Shareholder Meeting Feedback'), ('IPO Analysis', 'IPO Analysis'), ('Research Notes', 'Research Notes'), ('Sector Reports', 'Sector Reports'), ('Strategic Reports', 'Strategic Reports'), ('Economic Notes', 'Economic Notes'), ('Recommendation', 'Recommendation'), ('Stock Pitch', 'Stock Pitch'), ('Opinion on all stocks', 'Opinion on all stocks')], max_length=100),
        ),
    ]
