# Generated by Django 5.1.4 on 2026-08-19 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jdapublicationsapp', '0020_alter_publicationmodel_research_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publicationmodel',
            name='publication_date',
            field=models.DateField(db_index=True),
        ),
    ]
