# Generated by Django 4.2 on 2026-01-20 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paystack_test', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='paid',
        ),
        migrations.AddField(
            model_name='payment',
            name='status',
            field=models.CharField(choices=[('initialized', 'Initialized'), ('paid', 'Paid'), ('failed', 'Failed')], default='initialized', max_length=20),
        ),
        migrations.AlterField(
            model_name='payment',
            name='amount',
            field=models.PositiveIntegerField(help_text='Amount in kobo'),
        ),
    ]
