# Generated by Django 4.2 on 2025-12-02 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_alter_profile_id_alter_usergroups_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubscriptionPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('slug', models.SlugField(max_length=180, unique=True)),
                ('category', models.CharField(choices=[('customer', 'Customer'), ('institution', 'Institution')], default='customer', max_length=20)),
                ('price_monthly', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('price_quarterly', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('price_yearly', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('description', models.TextField(blank=True)),
                ('active', models.BooleanField(default=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
