# Generated by Django 5.1.4 on 2026-07-27 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_email_verification_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailverificationtoken',
            name='next_url',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
