# Generated by Django 4.2 on 2025-12-22 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jdasubscriptions', '0003_planfeature_subscriptionplan_features'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscriptionplan',
            name='code',
            field=models.SlugField(unique=True),
        ),
        migrations.AlterField(
            model_name='subscriptionplan',
            name='plan_type',
            field=models.CharField(choices=[('customer', 'Customer'), ('institution', 'Institution')], max_length=20),
        ),
    ]
