# Generated by Django 4.2 on 2026-01-01 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jdasubscriptions', '0005_remove_subscriptionplan_features_delete_planfeature_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customersubscription',
            old_name='ended_at',
            new_name='ends_at',
        ),
        migrations.RenameField(
            model_name='customersubscription',
            old_name='started_at',
            new_name='starts_at',
        ),
        migrations.AlterField(
            model_name='subscriptionplan',
            name='billing_period',
            field=models.CharField(choices=[('monthly', 'Monthly'), ('quarterly', 'Quarterly'), ('yearly', 'Yearly')], max_length=20),
        ),
    ]
