# Generated by Django 4.2 on 2026-01-16 21:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jdasubscriptions', '0007_alter_customersubscription_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='institutionsubscription',
            name='plan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='jdasubscriptions.subscriptionplan'),
        ),
    ]
