# Generated by Django 4.2 on 2026-01-22 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jdasubscriptions', '0008_alter_institutionsubscription_plan'),
    ]

    operations = [
        migrations.AddField(
            model_name='customersubscription',
            name='paystack_reference',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='customersubscription',
            name='paystack_status',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='subscriptionplan',
            name='paystack_reference',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='subscriptionplan',
            name='paystack_status',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
