# Generated by Django 4.2 on 2026-01-27 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jdasubscriptions', '0010_institutionsubscription_paystack_reference_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customersubscription',
            name='paystack_reference',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='institutionsubscription',
            name='paystack_reference',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
