# Generated by Django 5.1.4 on 2026-09-24 17:52

from django.db import migrations


GROUP_NAME = "Sales Staff"


def create_sales_staff_group(apps, schema_editor):
    Group = apps.get_model("auth", "Group")
    Group.objects.get_or_create(name=GROUP_NAME)


def delete_sales_staff_group(apps, schema_editor):
    Group = apps.get_model("auth", "Group")
    Group.objects.filter(name=GROUP_NAME).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('jdasubscriptions', '0022_reprice_akwaba_gold'),
    ]

    operations = [
        migrations.RunPython(create_sales_staff_group, delete_sales_staff_group),
    ]
