# Generated by Django 3.1.6 on 2022-04-19 23:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jdaanalyticsapp', '0032_auto_20220417_1047'),
    ]

    operations = [
        migrations.CreateModel(
            name='GuarantorModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guarantor', models.CharField(blank=True, max_length=25, null=True)),
                ('guarantor_pctg', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('guarantor_val', models.DecimalField(blank=True, decimal_places=2, max_digits=100, null=True)),
                ('security_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='jdaanalyticsapp.securitymodel')),
            ],
            options={
                'verbose_name_plural': 'GuarantorModel',
            },
        ),
    ]
