# Generated by Django 3.1.6 on 2022-04-15 10:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jdaanalyticsapp', '0032_restest'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ResTest',
        ),
    ]
