# Generated by Django 3.1.6 on 2022-04-19 23:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jdaanalyticsapp', '0033_guarantormodel'),
    ]

    operations = [
        migrations.RenameField(
            model_name='guarantormodel',
            old_name='security_id',
            new_name='security',
        ),
    ]
