# Generated by Django 3.1.6 on 2022-04-21 00:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jdaanalyticsapp', '0035_auto_20220420_1950'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guarantormodel',
            name='guarantor_pctg',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
    ]
