# Generated by Django 3.1.6 on 2022-04-29 20:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jdaanalyticsapp', '0042_auto_20220429_1606'),
    ]

    operations = [
        migrations.RenameField(
            model_name='securitymodel',
            old_name='issue',
            new_name='issuer',
        ),
    ]
