# Generated by Django 3.1.6 on 2022-05-06 18:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jdaanalyticsapp', '0045_auto_20220502_1511'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exchangemodel',
            name='security',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='exchanges', to='jdaanalyticsapp.securitymodel'),
        ),
    ]
