# Generated by Django 3.1.6 on 2022-05-06 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jdaanalyticsapp', '0046_auto_20220506_1425'),
    ]

    operations = [
        migrations.RenameField(
            model_name='exchangemodel',
            old_name='acronym',
            new_name='exchg_name',
        ),
        migrations.RemoveField(
            model_name='exchangemodel',
            name='name',
        ),
        migrations.AddField(
            model_name='exchangemodel',
            name='exchg_acronym',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterModelTable(
            name='exchangemodel',
            table='ExchangeModel',
        ),
    ]
