# Generated by Django 3.1.6 on 2022-05-06 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jdaanalyticsapp', '0047_auto_20220506_1525'),
    ]

    operations = [
        migrations.CreateModel(
            name='SecurityStockModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
                ('ticker', models.CharField(max_length=10)),
            ],
            options={
                'db_table': 'SecurityStockModel',
            },
        ),
    ]
