# Generated by Django 3.1.6 on 2022-05-08 15:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jdaanalyticsapp', '0048_securitystockmodel'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SecurityStockModel',
        ),
        migrations.RemoveField(
            model_name='exchangemodel',
            name='security',
        ),
        migrations.AddField(
            model_name='securitymodel',
            name='exchg',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='jdaanalyticsapp.exchangemodel'),
        ),
    ]
