# Generated by Django 3.1.6 on 2022-05-13 01:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jdaanalyticsapp', '0051_auto_20220512_2047'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='securitymodel',
            name='exchg',
        ),
        migrations.AddField(
            model_name='securitymodel',
            name='exchg',
            field=models.ManyToManyField(blank=True, null=True, to='jdaanalyticsapp.ExchangeModel'),
        ),
    ]
