# Generated by Django 3.1.6 on 2022-06-19 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jdaanalyticsapp', '0062_auto_20220524_2134'),
    ]

    operations = [
        migrations.AlterField(
            model_name='securitymodel',
            name='isin',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='securitymodel',
            name='ticker',
            field=models.CharField(blank=True, max_length=12, null=True),
        ),
    ]
