# Generated by Django 3.1.6 on 2022-06-20 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jdaanalyticsapp', '0063_auto_20220619_1703'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockmodel',
            name='lstn_dt',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='bondmodel',
            name='bnd_isu_dt',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='bondmodel',
            name='bnd_type',
            field=models.CharField(blank=True, choices=[('', 'Bond Type'), ('Redeemable in Shares', 'Redeemable in Shares'), ('Constant Redemption Bond', 'Constant Redemption Bond'), ('Deferred Constant Redemption Bond', 'Deferred Constant Redemption Bond'), ('In Fine Bond', 'In Fine Bond')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='bondmodel',
            name='dfrrd_rpymt_perd_units',
            field=models.CharField(blank=True, choices=[('', 'Deferred Repayment Period Units'), ('Monthly', 'Monthly'), ('Quarterly', 'Quarterly'), ('Semi-Annually', 'Semi-Annually'), ('Annually', 'Annually')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='bondmodel',
            name='duratn_units',
            field=models.CharField(blank=True, choices=[('', 'Duration Units'), ('Monthly', 'Monthly'), ('Quarterly', 'Quarterly'), ('Semi-Annually', 'Semi-Annually'), ('Annually', 'Annually')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='bondmodel',
            name='first_pay_dt',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='bondmodel',
            name='lst_pay_dt',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='bondmodel',
            name='pymt_perd_units',
            field=models.CharField(blank=True, choices=[('', 'Payment Period Unit'), ('Monthly', 'Monthly'), ('Quarterly', 'Quarterly'), ('Semi-Annually', 'Semi-Annually'), ('Annually', 'Annually')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='bondmodel',
            name='rpymt_mthd',
            field=models.CharField(blank=True, choices=[('', 'Repayment Method'), ('Sur Valeur', 'Sur Valeur'), ('Sur Valeur', 'Sur Valeur')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='bondmodel',
            name='rpymt_type',
            field=models.CharField(blank=True, choices=[('', 'Repayment Type'), ('Fixed rate', 'Fixed rate'), ('Variable rate', 'Variaible')], max_length=50, null=True),
        ),
    ]
