# Generated by Django 4.2 on 2025-04-20 23:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BondModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(max_length=100)),
                ('bond_name', models.CharField(max_length=100)),
                ('original_value', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=18, null=True)),
                ('coupon', models.DecimalField(decimal_places=4, default=0.0, max_digits=18)),
                ('current_value', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=18, null=True)),
                ('nbr_of_bonds', models.IntegerField(blank=True, null=True)),
                ('total_value', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=18, null=True)),
                ('institution_type', models.CharField(max_length=100)),
                ('entry_date', models.DateField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'BondModel',
                'unique_together': {('symbol', 'entry_date')},
            },
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name_plural': 'Cities',
            },
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name_plural': 'Countries',
            },
        ),
        migrations.CreateModel(
            name='Daily_stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stock', models.CharField(max_length=100)),
                ('daily_price', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='DepositaireModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('depositaire', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='InstitutionTypeModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inst_type', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Option',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='SociateDeGessionModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sociate_de_gession', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='TransactionFeesModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('commission_sgi', models.DecimalField(decimal_places=2, default=0.0, max_digits=18)),
                ('tps', models.DecimalField(decimal_places=2, default=0.0, max_digits=18)),
                ('country_sgi', models.DecimalField(decimal_places=2, default=0.0, max_digits=18)),
                ('commission_brvm', models.DecimalField(decimal_places=2, default=0.0, max_digits=18)),
                ('commission_dc_br', models.DecimalField(decimal_places=2, default=0.0, max_digits=18)),
                ('total_commission', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('actual_loss', models.DecimalField(decimal_places=2, default=0.0, max_digits=18)),
                ('potential_loss', models.DecimalField(decimal_places=2, default=0.0, max_digits=18)),
                ('entry_date', models.DateField(auto_now_add=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='StockDailyValuesModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticker', models.CharField(max_length=100)),
                ('daily_value', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=18, null=True)),
                ('target_value', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=18, null=True)),
                ('entry_date', models.DateField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'StockDailyValuesModel',
                'unique_together': {('ticker', 'entry_date')},
            },
        ),
        migrations.CreateModel(
            name='ResModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jdadev.country')),
            ],
            options={
                'verbose_name_plural': 'ResModel',
            },
        ),
        migrations.CreateModel(
            name='MutualFundModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sociate_de_gession', models.CharField(max_length=100)),
                ('depositaire', models.CharField(blank=True, max_length=100, null=True)),
                ('opcvm', models.CharField(max_length=100)),
                ('original_value', models.DecimalField(blank=True, decimal_places=4, default=0.0, max_digits=18, null=True)),
                ('current_value', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=18, null=True)),
                ('nbr_of_share', models.IntegerField(blank=True, null=True)),
                ('total_current_value', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=18, null=True)),
                ('entry_date', models.DateField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'MutualFundModel',
                'unique_together': {('opcvm', 'entry_date')},
            },
        ),
        migrations.CreateModel(
            name='CountryCityModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jdadev.city')),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jdadev.country')),
            ],
            options={
                'verbose_name_plural': 'CountryCityModel',
            },
        ),
        migrations.CreateModel(
            name='ClientProfileModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('liquid_assets', models.DecimalField(decimal_places=4, default=0.0, max_digits=18)),
                ('equity_and_rights', models.DecimalField(decimal_places=2, default=0.0, max_digits=18)),
                ('bonds', models.DecimalField(decimal_places=2, default=0.0, max_digits=18)),
                ('mutual_funds', models.DecimalField(decimal_places=2, default=0.0, max_digits=18)),
                ('profile_type', models.CharField(default='custom', max_length=50)),
                ('entry_date', models.DateField(auto_now_add=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'ClientProfileModel',
            },
        ),
        migrations.CreateModel(
            name='ClientPortfolioModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('liquid_assets', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=18, null=True)),
                ('equity_and_rights', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=18, null=True)),
                ('bonds', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=18, null=True)),
                ('mutual_funds', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=18, null=True)),
                ('entry_date', models.DateField(auto_now_add=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'ClientPortfolioModel',
            },
        ),
        migrations.CreateModel(
            name='ClientMutualFundsModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mu_original_value', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=18, null=True)),
                ('mu_current_value', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=18, null=True)),
                ('mu_nbr_of_share', models.IntegerField(blank=True, null=True)),
                ('mu_total_current_value', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=18, null=True)),
                ('mu_total_purchase_value', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=18, null=True)),
                ('mu_total_gain_or_loss', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=18, null=True)),
                ('entry_date', models.DateField(auto_now_add=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('depositaire', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='depositaires', to='jdadev.depositairemodel')),
                ('opcvm', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='opcvms', to='jdadev.mutualfundmodel')),
                ('sociate_de_gession', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sociate_de_gessions', to='jdadev.sociatedegessionmodel')),
            ],
            options={
                'verbose_name_plural': 'ClientMutualFundsModel',
            },
        ),
        migrations.CreateModel(
            name='ClientEquityAndRightsModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nbr_of_stocks', models.IntegerField(blank=True, null=True)),
                ('avg_weighted_cost', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=18, null=True)),
                ('daily_value', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=18, null=True)),
                ('total_current_value', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=18, null=True)),
                ('total_purchase_value', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=18, null=True)),
                ('total_gain_or_loss', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=18, null=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('stocks', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='stocks', to='jdadev.stockdailyvaluesmodel')),
            ],
            options={
                'verbose_name_plural': 'ClientEquityAndRightsModel',
            },
        ),
        migrations.CreateModel(
            name='ClientBondsModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nbr_of_shares', models.IntegerField(blank=True, null=True)),
                ('coupon', models.DecimalField(decimal_places=4, default=0.0, max_digits=18)),
                ('original_value', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=18, null=True)),
                ('current_value', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=18, null=True)),
                ('total_current_value', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=18, null=True)),
                ('total_purchase_value', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=18, null=True)),
                ('total_gain_or_loss', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=18, null=True)),
                ('bond_name', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bond_names', to='jdadev.bondmodel')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('institution_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='institution_types', to='jdadev.institutiontypemodel')),
                ('symbol', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='symbols', to='jdadev.bondmodel')),
            ],
            options={
                'verbose_name_plural': 'ClientBondsModel',
            },
        ),
        migrations.CreateModel(
            name='Client_portfolio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number_of_stocks', models.PositiveIntegerField()),
                ('total_value', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('stock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jdadev.daily_stock')),
            ],
        ),
        migrations.AddField(
            model_name='city',
            name='country',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cities', to='jdadev.country'),
        ),
    ]
