# Generated by Django 4.2 on 2025-09-15 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jdadev', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactionfeesmodel',
            name='actual_loss',
            field=models.DecimalField(decimal_places=3, default=0.0, max_digits=18),
        ),
        migrations.AlterField(
            model_name='transactionfeesmodel',
            name='commission_brvm',
            field=models.DecimalField(decimal_places=3, default=0.0, max_digits=18),
        ),
        migrations.AlterField(
            model_name='transactionfeesmodel',
            name='commission_dc_br',
            field=models.DecimalField(decimal_places=3, default=0.0, max_digits=18),
        ),
        migrations.AlterField(
            model_name='transactionfeesmodel',
            name='commission_sgi',
            field=models.DecimalField(decimal_places=3, default=0.0, max_digits=18),
        ),
        migrations.AlterField(
            model_name='transactionfeesmodel',
            name='country_sgi',
            field=models.DecimalField(decimal_places=3, default=0.0, max_digits=18),
        ),
        migrations.AlterField(
            model_name='transactionfeesmodel',
            name='potential_loss',
            field=models.DecimalField(decimal_places=3, default=0.0, max_digits=18),
        ),
        migrations.AlterField(
            model_name='transactionfeesmodel',
            name='total_commission',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='transactionfeesmodel',
            name='tps',
            field=models.DecimalField(decimal_places=3, default=0.0, max_digits=18),
        ),
    ]
