# Generated by Django 4.2 on 2025-06-01 17:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jdadev', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientequityandrightsmodel',
            name='stocks',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='stocks', to='jdadev.stockdailyvaluesmodel'),
        ),
    ]
