# Generated by Django 4.2 on 2025-04-21 13:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jdadev', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bondmodel',
            old_name='nbr_of_bonds',
            new_name='nbr_of_shares',
        ),
    ]
