# Generated by Django 4.2 on 2025-06-10 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jdadev', '0002_clientequityandrightsmodel_stocks'),
    ]

    operations = [
        migrations.AddField(
            model_name='bondmodel',
            name='yield_to_maturity',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=18, null=True),
        ),
    ]
