# Generated by Django 4.2 on 2025-04-21 15:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jdadev', '0002_rename_nbr_of_bonds_bondmodel_nbr_of_shares'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mutualfundmodel',
            old_name='nbr_of_share',
            new_name='nbr_of_shares',
        ),
    ]
