# Generated by Django 3.2.24 on 2024-04-24 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jdadev', '0002_stockdailyvaluesmodel_entry_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockdailyvaluesmodel',
            name='entry_date',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterUniqueTogether(
            name='stockdailyvaluesmodel',
            unique_together={('ticker', 'entry_date')},
        ),
    ]
