# Generated by Django 3.2.24 on 2024-04-26 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jdadev', '0003_auto_20240424_1311'),
    ]

    operations = [
        migrations.CreateModel(
            name='BondModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticker', models.CharField(max_length=100)),
                ('bond_name', models.CharField(max_length=100)),
                ('original_value', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=18, null=True)),
                ('coupon', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=18, null=True)),
                ('current_value', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=18, null=True)),
                ('nbr_of_shares', models.IntegerField(blank=True, null=True)),
                ('total_value', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=18, null=True)),
                ('institution_type', models.CharField(max_length=100)),
                ('entry_date', models.DateField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'BondModel',
                'unique_together': {('ticker', 'entry_date')},
            },
        ),
    ]
