# Generated by Django 3.2.24 on 2024-04-28 22:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('jdadev', '0004_bondmodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bondmodel',
            name='coupon',
            field=models.DecimalField(blank=True, decimal_places=4, default=0.0, max_digits=18, null=True),
        ),
        migrations.CreateModel(
            name='ClientPortfolioModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('liquid_assets', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=18, null=True)),
                ('equity_and_rights', models.DecimalField(blank=True, decimal_places=4, default=0.0, max_digits=18, null=True)),
                ('bonds', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=18, null=True)),
                ('entry_date', models.DateField(auto_now_add=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'ClientPortfolioModel',
            },
        ),
    ]
