# Generated by Django 4.2 on 2025-04-23 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jdadev', '0004_rename_nbr_of_shares_mutualfundmodel_nbr_of_share'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientprofilemodel',
            name='bonds',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=18),
        ),
        migrations.AlterField(
            model_name='clientprofilemodel',
            name='equity_and_rights',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=18),
        ),
        migrations.AlterField(
            model_name='clientprofilemodel',
            name='liquid_assets',
            field=models.DecimalField(blank=True, decimal_places=4, default=0.0, max_digits=18),
        ),
        migrations.AlterField(
            model_name='clientprofilemodel',
            name='mutual_funds',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=18),
        ),
        migrations.AlterField(
            model_name='clientprofilemodel',
            name='profile_type',
            field=models.CharField(blank=True, default='custom', max_length=50),
        ),
    ]
