# Generated by Django 4.2 on 2025-08-15 19:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jdadev', '0004_simstockpurchasedmodel'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='simstockpurchasedmodel',
            options={'verbose_name_plural': 'SimStockPurchasedModel'},
        ),
        migrations.RenameField(
            model_name='simstockpurchasedmodel',
            old_name='ticker',
            new_name='stock',
        ),
    ]
