# Generated by Django 4.2 on 2025-08-15 19:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jdadev', '0005_alter_simstockpurchasedmodel_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='simstockpurchasedmodel',
            old_name='stock',
            new_name='ticker',
        ),
    ]
