# Generated by Django 4.2 on 2025-04-23 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jdadev', '0005_alter_clientprofilemodel_bonds_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientprofilemodel',
            name='bonds',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=18),
        ),
        migrations.AlterField(
            model_name='clientprofilemodel',
            name='equity_and_rights',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=18),
        ),
        migrations.AlterField(
            model_name='clientprofilemodel',
            name='liquid_assets',
            field=models.DecimalField(decimal_places=4, default=0.0, max_digits=18),
        ),
        migrations.AlterField(
            model_name='clientprofilemodel',
            name='mutual_funds',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=18),
        ),
        migrations.AlterField(
            model_name='clientprofilemodel',
            name='profile_type',
            field=models.CharField(default='custom', max_length=50),
        ),
    ]
