# Generated by Django 3.2.24 on 2024-04-29 20:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jdadev', '0005_auto_20240428_1816'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientEquityAndRightsModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stocks', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='stocks', to='jdadev.stockdailyvaluesmodel')),
            ],
            options={
                'verbose_name_plural': 'ClientEquityAndRightsModel',
            },
        ),
    ]
