# Generated by Django 3.2.24 on 2024-05-06 19:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('jdadev', '0006_clientequityandrightsmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientequityandrightsmodel',
            name='client',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='auth.user'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='clientequityandrightsmodel',
            name='nbr_of_stocks',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
