# Generated by Django 4.2 on 2025-05-05 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jdadev', '0006_alter_clientprofilemodel_bonds_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ValidatorModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entry_date', models.DateField(unique=True)),
                ('anomalies', models.TextField(blank=True)),
                ('missing_data', models.TextField(blank=True)),
                ('insights', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-entry_date'],
            },
        ),
    ]
