# Generated by Django 4.2 on 2025-05-09 17:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('jdadev', '0007_validatormodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='SimHeldSecuritiesModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stock', models.CharField(max_length=100)),
                ('nbr_of_stocks', models.IntegerField()),
                ('avg_weighted_cost', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=18, null=True)),
                ('mkt_price', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=18, null=True)),
                ('gain_or_loss', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=18, null=True)),
                ('target_price', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=18, null=True)),
                ('potential_gain_or_loss', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=18, null=True)),
                ('selling_price', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=18, null=True)),
                ('decision', models.CharField(max_length=10)),
                ('sale_amount', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=18, null=True)),
                ('entry_date', models.DateField(auto_now_add=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'SimHeldSecuritiesModel',
            },
        ),
    ]
