# Generated by Django 4.2 on 2025-08-19 15:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('jdadev', '0007_simbondpurchasedmodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='SimMutualFundPurchasedModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('opcvm', models.CharField(max_length=100)),
                ('mu_nbr_of_share', models.IntegerField()),
                ('mu_current_value', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=18, null=True)),
                ('total_current_value', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=18, null=True)),
                ('percentage_purchase', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=18, null=True)),
                ('nbr_shares_to_buy', models.IntegerField()),
                ('net_purchase_price', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=18, null=True)),
                ('purchase_amount', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=18, null=True)),
                ('entry_date', models.DateField(auto_now_add=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'SimMutualFundPurchasedModel',
            },
        ),
    ]
