# Generated by Django 3.2.24 on 2024-05-17 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jdadev', '0008_clientequityandrightsmodel_avg_weighted_cost'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientportfoliomodel',
            name='liquid_assets',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=18, unique=True),
        ),
    ]
