# Generated by Django 4.2 on 2025-08-20 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jdadev', '0009_mutualfundmodel_performance'),
    ]

    operations = [
        migrations.AddField(
            model_name='simmutualfundpurchasedmodel',
            name='performance',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=18, null=True),
        ),
    ]
