# Generated by Django 3.2.24 on 2024-05-17 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jdadev', '0009_alter_clientportfoliomodel_liquid_assets'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientequityandrightsmodel',
            name='current_price',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=18, null=True),
        ),
    ]
