# Generated by Django 4.2 on 2025-08-22 22:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('jdadev', '0010_simmutualfundpurchasedmodel_performance'),
    ]

    operations = [
        migrations.CreateModel(
            name='SimStockSoldModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticker', models.CharField(max_length=100)),
                ('number_of_share', models.IntegerField()),
                ('daily_value', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=18, null=True)),
                ('target_value', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=18, null=True)),
                ('gp', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=18, null=True)),
                ('total_current_value', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=18, null=True)),
                ('percentage_sold', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=18, null=True)),
                ('nbr_shares_sold', models.IntegerField()),
                ('net_sell_price', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=18, null=True)),
                ('sold_amount', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=18, null=True)),
                ('entry_date', models.DateField(auto_now_add=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'SimStockPurchasedModel',
            },
        ),
    ]
