# Generated by Django 3.2.24 on 2024-05-17 22:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jdadev', '0010_clientequityandrightsmodel_current_price'),
    ]

    operations = [
        migrations.RenameField(
            model_name='clientequityandrightsmodel',
            old_name='current_price',
            new_name='daily_value',
        ),
    ]
