# Generated by Django 3.2.24 on 2024-05-25 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jdadev', '0012_client_portfolio_daily_stock'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientequityandrightsmodel',
            name='current_total_value',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=18, null=True),
        ),
    ]
