# Generated by Django 4.2 on 2025-08-24 19:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jdadev', '0012_simmutualfundsoldmodel_simbondsoldmodel'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='simmutualfundsoldmodel',
            options={'verbose_name_plural': 'SimMutualFundSoldModel'},
        ),
        migrations.RenameField(
            model_name='simmutualfundsoldmodel',
            old_name='nbr_shares_to_buy',
            new_name='nbr_shares_sold',
        ),
        migrations.RenameField(
            model_name='simmutualfundsoldmodel',
            old_name='net_purchase_price',
            new_name='net_sell_price',
        ),
        migrations.RenameField(
            model_name='simmutualfundsoldmodel',
            old_name='percentage_purchase',
            new_name='percentage_sold',
        ),
        migrations.RenameField(
            model_name='simmutualfundsoldmodel',
            old_name='purchase_amount',
            new_name='sold_amount',
        ),
    ]
