# Generated by Django 3.2.24 on 2024-05-26 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jdadev', '0013_clientequityandrightsmodel_current_total_value'),
    ]

    operations = [
        migrations.RenameField(
            model_name='clientequityandrightsmodel',
            old_name='current_total_value',
            new_name='total_current_value',
        ),
        migrations.AddField(
            model_name='clientequityandrightsmodel',
            name='total_purchase_value',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=18, null=True),
        ),
    ]
