# Generated by Django 4.2 on 2025-08-24 21:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jdadev', '0013_alter_simmutualfundsoldmodel_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='simbondsoldmodel',
            old_name='nbr_shares_to_buy',
            new_name='nbr_shares_sold',
        ),
        migrations.RenameField(
            model_name='simbondsoldmodel',
            old_name='net_purchase_price',
            new_name='net_sell_price',
        ),
        migrations.RenameField(
            model_name='simbondsoldmodel',
            old_name='percentage_purchase',
            new_name='percentage_sold',
        ),
        migrations.RenameField(
            model_name='simbondsoldmodel',
            old_name='purchase_amount',
            new_name='sold_amount',
        ),
    ]
