# Generated by Django 3.2.24 on 2024-05-26 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jdadev', '0014_auto_20240526_1033'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientequityandrightsmodel',
            name='total_gain_or_lost',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=18, null=True),
        ),
    ]
