# Generated by Django 3.2.24 on 2024-05-27 12:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jdadev', '0015_clientequityandrightsmodel_total_gain_or_lost'),
    ]

    operations = [
        migrations.RenameField(
            model_name='clientequityandrightsmodel',
            old_name='total_gain_or_lost',
            new_name='total_gain_or_loss',
        ),
    ]
