# Generated by Django 3.2.24 on 2024-05-28 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jdadev', '0019_clientbondsmodel_institution_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientportfoliomodel',
            name='liquid_assets',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=18),
        ),
    ]
