# Generated by Django 3.2.24 on 2024-05-29 20:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jdadev', '0020_alter_clientportfoliomodel_liquid_assets'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientbondsmodel',
            name='bond_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bond_names', to='jdadev.bondmodel'),
        ),
    ]
