# Generated by Django 3.2.24 on 2024-06-09 00:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jdadev', '0021_clientbondsmodel_bond_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Option',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
    ]
