# Generated by Django 3.2.24 on 2024-06-10 23:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jdadev', '0024_auto_20240610_1912'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='countrycitymodel',
            options={'verbose_name_plural': 'CountryCityModel'},
        ),
    ]
