# Generated by Django 3.2.24 on 2024-06-17 21:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jdadev', '0025_alter_countrycitymodel_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='InstitutionTypeModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='bondmodel',
            name='institution_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bonds', to='jdadev.institutiontypemodel'),
        ),
    ]
