# Generated by Django 3.2.24 on 2024-06-17 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jdadev', '0026_auto_20240617_1720'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bondmodel',
            name='institution_type',
            field=models.CharField(max_length=100),
        ),
    ]
