# Generated by Django 3.2.24 on 2024-06-17 21:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jdadev', '0027_alter_bondmodel_institution_type'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='institutiontypemodel',
            options={'verbose_name_plural': 'InstitutionTypeModel'},
        ),
    ]
