# Generated by Django 3.2.24 on 2024-06-17 21:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jdadev', '0028_alter_institutiontypemodel_options'),
    ]

    operations = [
        migrations.DeleteModel(
            name='InstitutionTypeModel',
        ),
    ]
