# Generated by Django 3.2.24 on 2024-06-18 13:27

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('jdadev', '0029_delete_institutiontypemodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientbondsmodel',
            name='institution_type',
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
    ]
