# Generated by Django 3.2.24 on 2024-06-18 20:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jdadev', '0031_alter_clientbondsmodel_institution_type'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ClientBondsModel',
        ),
    ]
