# Generated by Django 3.2.24 on 2024-06-20 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jdadev', '0033_clientbondsmodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='InstitutionTypeModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inst_type', models.CharField(max_length=200)),
            ],
        ),
    ]
