# Generated by Django 3.2.24 on 2024-06-20 18:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jdadev', '0035_alter_clientbondsmodel_institution_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientbondsmodel',
            name='original_value',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='original_values', to='jdadev.bondmodel'),
        ),
    ]
