# Generated by Django 3.2.24 on 2024-06-24 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jdadev', '0036_clientbondsmodel_original_value'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientbondsmodel',
            name='original_value',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=18, null=True),
        ),
    ]
