# Generated by Django 3.2.24 on 2024-06-24 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jdadev', '0037_alter_clientbondsmodel_original_value'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientbondsmodel',
            name='nbr_of_bonds',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
