# Generated by Django 3.2.24 on 2024-06-24 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jdadev', '0038_clientbondsmodel_nbr_of_bonds'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientbondsmodel',
            name='total_current_value',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=18, null=True),
        ),
    ]
