# Generated by Django 3.2.24 on 2024-06-24 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jdadev', '0039_clientbondsmodel_total_current_value'),
    ]

    operations = [
        migrations.CreateModel(
            name='MutualFundModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sociate_de_gession', models.CharField(max_length=100)),
                ('depositaire', models.CharField(max_length=100)),
                ('opcvm', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=18, null=True)),
                ('original_value', models.DecimalField(blank=True, decimal_places=4, default=0.0, max_digits=18, null=True)),
                ('current_value', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=18, null=True)),
                ('nbr_of_shares', models.IntegerField(blank=True, null=True)),
                ('entry_date', models.DateField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'MutualFundModel',
                'unique_together': {('opcvm', 'entry_date')},
            },
        ),
    ]
