# Generated by Django 3.2.24 on 2024-06-24 23:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jdadev', '0040_mutualfundmodel'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mutualfundmodel',
            old_name='nbr_of_shares',
            new_name='nbr_of_share',
        ),
    ]
