# Generated by Django 3.2.24 on 2024-06-24 23:43

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('jdadev', '0041_rename_nbr_of_shares_mutualfundmodel_nbr_of_share'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mutualfundmodel',
            name='opcvm',
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
    ]
