# Generated by Django 3.2.24 on 2024-07-05 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jdadev', '0044_alter_clientmutualfundsmodel_opcvm'),
    ]

    operations = [
        migrations.AlterField(
            model_name='depositairemodel',
            name='depositaire',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
