# Generated by Django 3.2.24 on 2024-07-05 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jdadev', '0045_alter_depositairemodel_depositaire'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mutualfundmodel',
            name='depositaire',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
