# Generated by Django 3.2.24 on 2024-07-05 23:28

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('jdadev', '0046_alter_mutualfundmodel_depositaire'),
    ]

    operations = [
        migrations.AlterField(
            model_name='depositairemodel',
            name='depositaire',
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
    ]
