# Generated by Django 3.2.24 on 2024-07-06 18:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jdadev', '0047_alter_depositairemodel_depositaire'),
    ]

    operations = [
        migrations.AlterField(
            model_name='depositairemodel',
            name='depositaire',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='depositaires', to='jdadev.mutualfundmodel'),
        ),
    ]
