# Generated by Django 3.2.24 on 2024-07-06 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jdadev', '0048_alter_depositairemodel_depositaire'),
    ]

    operations = [
        migrations.AlterField(
            model_name='depositairemodel',
            name='depositaire',
            field=models.CharField(max_length=100),
        ),
    ]
