# Generated by Django 3.2.24 on 2024-07-06 22:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jdadev', '0049_alter_depositairemodel_depositaire'),
    ]

    operations = [
        migrations.RenameField(
            model_name='clientmutualfundsmodel',
            old_name='current_value',
            new_name='mu_current_value',
        ),
        migrations.RenameField(
            model_name='clientmutualfundsmodel',
            old_name='nbr_of_share',
            new_name='mu_nbr_of_share',
        ),
        migrations.RenameField(
            model_name='clientmutualfundsmodel',
            old_name='original_value',
            new_name='mu_original_value',
        ),
    ]
