# Generated by Django 4.2 on 2025-03-22 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jdadev', '0052_clientmutualfundsmodel_mu_total_current_value'),
    ]

    operations = [
        migrations.RenameField(
            model_name='clientbondsmodel',
            old_name='nbr_of_bonds',
            new_name='nbr_of_shares',
        ),
        migrations.AddField(
            model_name='clientbondsmodel',
            name='coupon',
            field=models.DecimalField(blank=True, decimal_places=4, default=0.0, max_digits=18, null=True),
        ),
        migrations.AlterField(
            model_name='clientportfoliomodel',
            name='liquid_assets',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=18, null=True),
        ),
    ]
