# Generated by Django 4.2 on 2025-03-22 17:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jdadev', '0053_rename_nbr_of_bonds_clientbondsmodel_nbr_of_shares_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bondmodel',
            old_name='nbr_of_shares',
            new_name='nbr_of_bonds',
        ),
    ]
