# Generated by Django 4.2 on 2025-03-23 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jdadev', '0054_rename_nbr_of_shares_bondmodel_nbr_of_bonds'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bondmodel',
            name='coupon',
            field=models.DecimalField(decimal_places=4, default=0.0, max_digits=18),
        ),
    ]
