# Generated by Django 4.2 on 2025-03-23 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jdadev', '0055_alter_bondmodel_coupon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientbondsmodel',
            name='coupon',
            field=models.DecimalField(decimal_places=4, default=0.0, max_digits=18),
        ),
    ]
