# Generated by Django 4.2 on 2025-03-23 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jdadev', '0056_alter_clientbondsmodel_coupon'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientbondsmodel',
            name='total_gain_or_lost',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=18, null=True),
        ),
        migrations.AddField(
            model_name='clientbondsmodel',
            name='total_purchase_value',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=18, null=True),
        ),
    ]
