# Generated by Django 4.2 on 2025-03-23 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jdadev', '0057_clientbondsmodel_total_gain_or_lost_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientbondsmodel',
            name='current_value',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=18, null=True),
        ),
    ]
