# Generated by Django 4.2 on 2025-03-23 21:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jdadev', '0058_clientbondsmodel_current_value'),
    ]

    operations = [
        migrations.RenameField(
            model_name='clientbondsmodel',
            old_name='total_gain_or_lost',
            new_name='total_gain_or_loss',
        ),
    ]
