# Generated by Django 4.2 on 2025-03-27 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jdadev', '0059_rename_total_gain_or_lost_clientbondsmodel_total_gain_or_loss'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientmutualfundsmodel',
            name='mu_total_gain_or_loss',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=18, null=True),
        ),
        migrations.AddField(
            model_name='clientmutualfundsmodel',
            name='mu_total_purchase_value',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=18, null=True),
        ),
    ]
