# Generated by Django 4.2 on 2025-04-02 15:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('jdadev', '0060_clientmutualfundsmodel_mu_total_gain_or_loss_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientProfileModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('liquid_assets', models.DecimalField(blank=True, decimal_places=4, default=0.0, max_digits=18, null=True)),
                ('equity_and_rights', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=18, null=True)),
                ('bonds', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=18, null=True)),
                ('mutual_funds', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=18, null=True)),
                ('entry_date', models.DateField(auto_now_add=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'ClientProfileModel',
            },
        ),
    ]
