# Generated by Django 4.2 on 2025-04-03 18:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jdadev', '0061_clientprofilemodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientprofilemodel',
            name='profile_type',
            field=models.CharField(default=datetime.datetime(2025, 4, 3, 18, 37, 32, 276683, tzinfo=datetime.timezone.utc), max_length=50),
            preserve_default=False,
        ),
    ]
