# Generated by Django 4.2 on 2025-04-06 18:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('jdadev', '0062_clientprofilemodel_profile_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientprofilemodel',
            name='bonds',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=18),
        ),
        migrations.AlterField(
            model_name='clientprofilemodel',
            name='equity_and_rights',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=18),
        ),
        migrations.AlterField(
            model_name='clientprofilemodel',
            name='liquid_assets',
            field=models.DecimalField(decimal_places=4, default=0.0, max_digits=18),
        ),
        migrations.AlterField(
            model_name='clientprofilemodel',
            name='mutual_funds',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=18),
        ),
        migrations.CreateModel(
            name='TransactionFeesModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('commision_sgi', models.DecimalField(decimal_places=2, default=0.0, max_digits=18)),
                ('tps', models.DecimalField(decimal_places=2, default=0.0, max_digits=18)),
                ('country_sgi', models.DecimalField(decimal_places=2, default=0.0, max_digits=18)),
                ('entry_date', models.DateField(auto_now_add=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'TransactionFeesModel',
            },
        ),
    ]
