# Generated by Django 4.2 on 2025-04-06 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jdadev', '0063_alter_clientprofilemodel_bonds_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transactionfeesmodel',
            name='commussion_brvm',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=18),
        ),
        migrations.AddField(
            model_name='transactionfeesmodel',
            name='commussion_dc_br',
            field=models.CharField(default=0.0, max_length=50),
            preserve_default=False,
        ),
    ]
