# Generated by Django 4.2 on 2025-04-12 18:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jdadev', '0064_transactionfeesmodel_commussion_brvm_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transactionfeesmodel',
            old_name='commision_sgi',
            new_name='commission_brvm',
        ),
        migrations.RenameField(
            model_name='transactionfeesmodel',
            old_name='commussion_dc_br',
            new_name='commission_dc_br',
        ),
        migrations.RenameField(
            model_name='transactionfeesmodel',
            old_name='commussion_brvm',
            new_name='commission_sgi',
        ),
    ]
