# Generated by Django 4.2 on 2025-04-12 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jdadev', '0065_rename_commision_sgi_transactionfeesmodel_commission_brvm_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactionfeesmodel',
            name='commission_dc_br',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=18),
        ),
    ]
