# Generated by Django 4.2 on 2025-04-12 18:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jdadev', '0066_alter_transactionfeesmodel_commission_dc_br'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='transactionfeesmodel',
            options={},
        ),
    ]
