# Generated by Django 4.2 on 2025-04-14 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jdadev', '0067_alter_transactionfeesmodel_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientprofilemodel',
            name='profile_type',
            field=models.CharField(default='custom', max_length=50),
        ),
    ]
