# Generated by Django 4.2 on 2025-04-15 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jdadev', '0068_alter_clientprofilemodel_profile_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='transactionfeesmodel',
            name='actual_loss',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=18),
        ),
        migrations.AddField(
            model_name='transactionfeesmodel',
            name='potential_loss',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=18),
        ),
    ]
