# Generated by Django 4.2 on 2025-04-19 18:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jdadev', '0069_transactionfeesmodel_actual_loss_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transactionfeesmodel',
            name='total_commission',
            field=models.DecimalField(decimal_places=2, default=datetime.datetime(2025, 4, 19, 18, 13, 23, 320850, tzinfo=datetime.timezone.utc), max_digits=8),
            preserve_default=False,
        ),
    ]
