# Generated by Django 4.2 on 2025-04-19 18:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jdadev', '0070_transactionfeesmodel_total_commission'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transactionfeesmodel',
            name='actual_loss',
        ),
        migrations.RemoveField(
            model_name='transactionfeesmodel',
            name='commission_brvm',
        ),
        migrations.RemoveField(
            model_name='transactionfeesmodel',
            name='commission_dc_br',
        ),
        migrations.RemoveField(
            model_name='transactionfeesmodel',
            name='commission_sgi',
        ),
        migrations.RemoveField(
            model_name='transactionfeesmodel',
            name='country_sgi',
        ),
        migrations.RemoveField(
            model_name='transactionfeesmodel',
            name='potential_loss',
        ),
        migrations.RemoveField(
            model_name='transactionfeesmodel',
            name='total_commission',
        ),
        migrations.RemoveField(
            model_name='transactionfeesmodel',
            name='tps',
        ),
    ]
