# Generated by Django 4.2 on 2025-04-19 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jdadev', '0071_remove_transactionfeesmodel_actual_loss_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transactionfeesmodel',
            name='actual_loss',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=18),
        ),
        migrations.AddField(
            model_name='transactionfeesmodel',
            name='commission_brvm',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=18),
        ),
        migrations.AddField(
            model_name='transactionfeesmodel',
            name='commission_dc_br',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=18),
        ),
        migrations.AddField(
            model_name='transactionfeesmodel',
            name='commission_sgi',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=18),
        ),
        migrations.AddField(
            model_name='transactionfeesmodel',
            name='country_sgi',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=18),
        ),
        migrations.AddField(
            model_name='transactionfeesmodel',
            name='potential_loss',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=18),
        ),
        migrations.AddField(
            model_name='transactionfeesmodel',
            name='tps',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=18),
        ),
    ]
