# Generated by Django 4.2 on 2025-04-19 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jdadev', '0072_transactionfeesmodel_actual_loss_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transactionfeesmodel',
            name='total_commission',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=8),
            preserve_default=False,
        ),
    ]
