# Generated by Django 4.2 on 2025-04-20 19:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jdadev', '0073_transactionfeesmodel_total_commission'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transactionfeesmodel',
            name='total_commission',
        ),
    ]
