# Generated by Django 4.2 on 2025-04-20 19:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jdadev', '0074_remove_transactionfeesmodel_total_commission'),
    ]

    operations = [
        migrations.AddField(
            model_name='transactionfeesmodel',
            name='total_commission',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=8),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='ResModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jdadev.country')),
            ],
            options={
                'verbose_name_plural': 'ResModel',
            },
        ),
    ]
