# Generated by Django 4.2 on 2025-04-20 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jdadev', '0075_transactionfeesmodel_total_commission_resmodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactionfeesmodel',
            name='total_commission',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
    ]
