# Generated by Django 4.2 on 2025-04-20 22:40
from django.db import migrations, models

class Migration(migrations.Migration):

    dependencies = [
        ('jdadev', '0076_transactionfeesmodel_total_commission_resmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='transactionfeesmodel',
            name='total_commission',
            field=models.DecimalField(max_digits=12, decimal_places=2, null=True, blank=True),
        ),
    ]
